apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mhUFBCfGxFkcrfwfhRi1JyjvSCtR9lJ4Ir/5UF0/gBoNrgum/D8yrw==,iv:U3jIDsHHr8XMqUsSg8RZntUsFQvGUfNu+j46do5C0Gg=,tag:dwZVYkAOs69xBepUCEXDtA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cEZMdnkvakorQzY1QkVU
            OEFyNzQ0UDlmS0EwNThWcDdac3J2M2VxSEhrCkR6eVo0MU9SZlQ3UjFqYUZrbG9B
            Qmc5Q2dGa1g0SXgxQmUrU1F0Y1pDeE0KLS0tIG54cGtJWE1jS3VkbXA3OXIxcDY1
            bi9IbERYZUVxMEpLOFVvcFNQVVVndHcKlhYgbFWnPRM1iSXnkevaxmxibD96oeCb
            5zFHXYkjJe99wF291n070L3M1et2RofSWYFIaruQdIF/tuUuOu89pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T08:06:41Z"
    mac: ENC[AES256_GCM,data:ToX3T8sTjW9ZZakocJ/mFhaznkJ85bzufcIUvL1MYau3U2RM9EYBlhqt/b8vnmQoceKVyrcwMlBFMtf3M9umb0T3w0nf010q6EXy+qJOaMdlqB5AyhS3qp38k7evE12ytqAZCPdeKU8KGJ9xXcElOCNi2T3mtxZlpDM5BT2HCkg=,iv:tzSZ5h4S/5yFkhuUyn5QMzfPJ9FsYRqTnT/UvbnaGAY=,tag:EXtaDorfEEVfzy1wCwFkbA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
