apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qTo4vej/7T8IxK7g5Lj8jU6oT0H5LGmuY1dQSvVbUC93FzYZzY2q8Q==,iv:jkyVvAzTJFTWF9DR7yXAOVFrXe7WZIQV3dg/D8wTWpI=,tag:piJscjFaszH8heNX8TstCw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmLzNJbUlKUDJmZDdqMUow
            bVRTc2hLbUduVVZDVUFNY0o4VWlSNzhqa2xjCmRsaGFIamMyMmdwZmxJSXF4OUtM
            NVpMbE5KclRBMmlGVlJ1TkxhbGNjRDAKLS0tIFFta2ZXeGlOYW5JS3FJbS9Lc0Vh
            c2lRZ1NhS1Uza3FNbFhBTVJJeGwyaUkK2rFZJvENBCQpr2mYD3D4aaySUb9HB6ct
            2iI+1pC5YFJDrdPGI5b0BYjYZiVULUmumja5XrXaKcjYaBr2T6Y9Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T23:45:49Z"
    mac: ENC[AES256_GCM,data:47oIwOPNxNTttUEGYjILp+dQPZJt7nxwHW+1UULa/pN1ePa3jN65BYkXIKRbqPooKUcR84gv4GGi8PyNoljjjJmeWtZ0/FldSDjpVvHNdiMeoEsvi9JPb4WeFyithqqLP+c35C8iCOVerf3mdJJdRv8E2nmYt5XA0p5q3WScc8k=,iv:dKGxCNdPdY62zkUIytQFDS/DruTr9yrq5NV7bTp/CrM=,tag:1peQV5SE2mUvV1OSd3WIuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
