apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:W+DOg/5ZZc6NEjNehCTPMMb7UJGTBwihj9SwrY+EEG1dBAU6N4fbKA==,iv:mB/3WQfb2BwXKgrQ6pC20BRY6UZiu2eNcyFuZkk3cDM=,tag:PwlyQI1RQ8euVEaLkA529Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K29GNmVONlJ4bk5jUTJL
            MFFTQmxzVnVaT0VDZWtyNS8xaCs3cXh6WkJnCkpBK25jK3ZETjh1SG5vM2RtVU85
            bGZGdERFemZMNnpSSkRiWUlLVWF4SW8KLS0tIDR4L29JVmFGWDJ4Y2k0S2dTSXp2
            WUl0bGh6WDQ5UUFEWmhzZU0vQVRtR28KV3d5lDMw8Z4ssWeZnaYkUsg5c9PZdPgG
            pWaETIBqUZwJVJbQ0yQ8GbrvS6EE+HZCQtLbNOKpi4JwtniB6YcBMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:42:02Z"
    mac: ENC[AES256_GCM,data:0Lks43BTUf4iHo4AIfYSSAHhEngQgLiv90fDKxjEo7YeWa+2+ahNe04YwzOy6e3zJGzC336ZZr+5RevrGVu8m8cys9LBiROEKo9F+UlmAQ9IjRGU4F67Jx33gLkEnvuDR9ksG4gVGbboDK6nK4+lYsmaHBpubOnE45C5HURW31M=,iv:yUC54n9n9+7mxEB6GKR01dB3zGtQR0j7QmXB4KH47aI=,tag:a1eL3cG3VgxYC479H4rqoA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
