# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myspeed
  namespace: myspeed
spec:
  interval: 15m
  chart:
    spec:
      chart: myspeed
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TIMEZONE}

    credentials:
      s3:
        type: s3
        url: ${S3_URL}
        bucket: ${S3_BUCKET}
        accessKey: ${S3_accessKey}
        secretKey: ${S3_secretKey}
        encrKey: ${S3_secretKey}

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          homepage:
            enabled: true
            group: Monitoring
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: myspeed.${DOMAIN_0}

    persistence:
      data:
        volsync:
          - name: r2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true

    resources:
      limits:
        cpu: 4000m
