# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 27.8.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TIMEZONE}

    credentials:
      s3:
        type: s3
        url: ${S3_URL}
        bucket: ${S3_BUCKET}
        accessKey: ${S3_accessKey}
        secretKey: ${S3_secretKey}
        encrKey: ${S3_encrKey}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: auth.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix

    authentik:
      email:
        host: smtp.gmail.com
        usernarme: ${SERV_EMAIL}
        password: ${AUTHENTIK_EMAIL_PASSWORD}
        from: "Auth Admin <no-reply@${DOMAIN_1}>"
      geoip:
        enabled: true
        accountID: ${AUTHENTIK_GEOIP_ID}
        licenseKey: ${AUTHENTIK_GEOIP_KEY}
      outposts:
        proxy:
          enabled: false
          token: ""
        radius:
          enabled: false
          token: ""
        ldap:
          enabled: false
          token: ""