apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/6cU6wknl1ly8lhWG9PDnMZt4Ccp3yaT8rain0f+KNw16KP+qfKlhfwtDReYShpSnHwBuEwCeNBnetzaPsvBCofmURsj5PGfGIZCRPG9ceeTgVuEfD+psM4S/O32Ja/KKD0NCRGx2cBEs8DQpt4aHioQgPTLu0ENNCBEWnoP4J8miclyiajWbKwQTm2RjwWRcdyh3YFqPTPg3r7MB3b3bDZlGcjEhrP0jCjygNAFi7Lo1x2wAEMUWxllbhry8uR9/ldRDDc8kI5LBw2bqysP9OAQ9h7uUYrBa4sUyreV2fXHBBQPfDb/Fif4MGrXpWljh9URYUzCO0drVhiG1uZUgKRSHJlcRaetrC6MhP8MERiNLwEw8z+ImEu5AwdolIhH,iv:SAd/6Ea+azdZ5tUbGZz4ZxqSQqmrLtMQS11vKFs2HWo=,tag:G+OhdH8roHRGbiX0MeMT3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:oLTTjk840zMxbKqq2eqE++2OfskjLg9cZqLgdcW+/1Jw0YuYbp7K4aGWmxxAq3dnE43sd8ylsJHd8vkoNCsElhdzBVt91AAeIdOoMm0umW9xE3hLBdlT8YLVUSUvbryBX3UEGR8lJvlgqZE33mZ0SGSJvXJzMoTuBN4ZX9UJrv6hSFHMulj+73b0d/IqtgyPmLr5jc4F2SEuliNCSQEaLgNMRbEqqfjYcCDE4+aaPlqgG6NxcUxyqdl0i9XQkXrs7qcfUcsuas2t/4Bupw==,iv:EBRaKWxJDUyM+LoxQhi9+jaFKexxAXnsWqXT4Y5gc+U=,tag:RvHOctvAncsZkJigMMiVVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:7zME7txDbDxH8SvSLYNrHZNdgaqoFVngWuVD397/FeeVT47uB3o7e80URqh87Dfrf3bUL8Hq3cDh9mUcZsNK2Lx7lyu+BZ7jbEVYWVvKXzEosX61jrxhr9XeIalDFVLBog1hCylmIU91F9MNjG9pUiYbpiEiJ/7FgB7Va39zXRcuDD1sd5rYO3S6ZOQ8PbPfhqPvL5yYJaFXNb7r9IkH60Rv8kEAtUUqP5xI,iv:+vkybATyVRbie8yPqC9fvv/qeR84kD9znADg/jPYQ+4=,tag:w8t10g4TDem63/1eIRJQ2w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYckFnRjJrN0pjRGNtVThR
            Vjl6OVJJalBySkUwYW1ZMVJtdHJvTWN0aTJrCm1mZTFRcmp3WHhqNURaY1NQeWJm
            Z3pDTHYyUDFodk9iV2dndXhzOWVJbm8KLS0tIDdZMEZVOVVlMmVxRTl4WlZGMjZl
            MmZMOHEyN0RZZzVUN3cvS29la0hKbkEKQdqdR7+aX+JoY1qL6orTErdQu6RiKg+E
            /Ch2VLAOh3V1N0L+asurjbHbT1UY9DIwQcFsVrrIHvLuL0F1tlgJBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T12:57:04Z"
    mac: ENC[AES256_GCM,data:O9yo7LOizFoek8ZtOeY6gG4bxJRuXUuDe8wukSYvUSsOSu/oIr2pcO8OTOJTPHLZK4zq3nE08cNhXSrp8ziR+15e5aydrPs/WFirIp9sbKuX4QbwIkaKK1rt1qW7Iqp8kuaOBALn9DRC92PYEsixcyZTimzq9pLLGZUwGt407t8=,iv:0qbds08zMIf7XzBSUhHbwviiHT3qIdAUlypMKGwmXZc=,tag:KfndwoQo1cgyNA24HpItyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
