apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:40srZBmXgCthlsMRjMjwZTzidP5tJ41LWym5vVsackrcvjstQF8in+gqJjsG1PSRmldvceKQwn2QSCOrNZp2UpobDok2Uo0/tBHSa8TjJhUCmTBGCxRTldSQIFZ8QKZ7vygOxwqB+3yUdPIdw3PvaZ69ClQ8oI8eB/K0ql8unHEGiv5kuIhIPo84/HBYjeUc37r/HBB+g1wTsUAXnJ6fH8cHo4XzP3PNkd/Ttsgcy92+PFjnkDkO5dZCId1FqxamjiVU/HGsQ42pmjpsRjp0LyIkZMO+Qwzlp7bnB60MOishOiV1qqs4H9/k41O3L4IET7UWFlnhuu7SDrbgz1Y4Gpvvfwgz1ED3GDxtlJixOVa7Kj5o+EqIe+EUs1qNvK0S,iv:cYXjOD0yV2SrQaTadBkQrsIZTD0m+i6CILO+W6mnaq0=,tag:XR+vq07Lg2IxpxXpcc+SUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:2mfhvOOKHLPT366ucxvnGSr9KM4SaPHJTJN9y+GyDcZtcbODK/4TK/4p1zqZDtXCee8ITKk7NkHBVVv8ke2TsmAyOVPXPf5v0AirdFKyTpJjsfCWyAfcYFRB5NKmWjBg94m5CuAD8WfxiMwtp/usR5LapYexD5ppKyaodmVCTIE42jqGCi1cq4DDi6uATYAzRXuufNLttpuZo0h7RlepN4sYWxgec8rfrM6rUFUoX/1BGaEOWelZ2UdBpT2TAve6r3oxtp+jPJYtEgSr1w==,iv:2PFAKGf2IFzscIYq+ki2DifyXk9w5nQ9yuT6a6Hq4RE=,tag:DqJeh4+BObECscAQcSN5lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pmz6YL+UiFVKXQKaE5HwihLs4zclRs5KJTbeF0G6rIHt4Zx7i3EiamkFppwF8aYCb2iAxgz0GAbea5CeSlSNc7JX4s/+NZGs5QJQB0aqXFR0ELXJBcPWEnOBjFTJ28lqQoSBZVmvBO/4gMYgAwt8vjnFzsJbsKRyxUgvDZdyejyeINWGlsLJzzRDfu1ANpRu9PDfI80nw+zqL8OC/ynNlf8cCdD8jhM6OpN/,iv:y23AnaQv0KoEZotbqXmrVE51n8qgW+4P+LzTYElyiUA=,tag:nXf+Ex0XY19t8NZrB6pyWQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkxEMlRRWnNvZkxjeXJQ
            Mml6cEJ1VjBKVjRMVHJNNmNBaktSdGZpTUNNClFhYmFUZ0xjUVM2WXRPbjRORW9D
            OGdJS0hBREN2SHRRNTFrWXV5bEZIR1kKLS0tIHhXSDBaWHdrbXAvc3ZrY2poQ3pE
            eUdleWZBaThCSWFYNUxGdU5FeG5SQmcKQh93DS/5t8ZF3ZffdbZsD/9XcFIYUfSs
            JI3N22zwsm6RqB3uDIkz+dCdmrIAfX1hxVWNVImJ8rLiwtY4nAQPww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T07:00:35Z"
    mac: ENC[AES256_GCM,data:ZsLe1lDpFoFpUKea95pui9xYe2nRkjNFCiHOrdxDaf0hXdNbc7bwbe4OOhGIKobg5JHdcRcIrGw83Ci4xOA5b2mT7Mo1CUKcmGhPujiUHUZ9fFIjfvonaNlZ5kDYOx52kKQfbzOHadpQkr+KbDTsuWUD8E8PSFHR5UFmgW+cBkI=,iv:FTkK99k6ENTw1u+I38UlyFel8uj+47cR4AnETxyu4rA=,tag:ZBPDq1XbFLj3xs3Q3a/tjA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
