apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:asOXNqkLgOCvUob2SycrcXjbNcH6K7q1UXp41L+E0EqOtMtGrqhPU05+3om9Hyo0Afr5qQx2QVj7kgLVAq1eVs7/XJjYvJbLMINmWRk7YJ/7TSuW3rWIg9ruX9rZCaATXG307GMBEuzLOsUzpSsl93tm3TinDlE2EXbZpTEaQhTkrofiITlywtJM2HJ1iBGYI7H8dyu/JvZ1arUwMwWcQ12NgjJSJ3YplFED5AAx+9LV7XCFP9eEE5Bh2jP80nPus2M++scv6ML0ML6pDhnMLSTifVOrdTuWagjPxfeAsBk+qJPCV5gnL2sKOt7EHK6BxXyZ6eOaCjvZFbSoqvkNgfSeAzIVwz3K2taOh3y1y7AfRcfkC/LBFRLn74YbK/u6,iv:i1c0dlerGVE8nXa4s0a6ECFnD7PB9/1ckpWDZcsAF4c=,tag:p1ZM+Abq4RTVl6ttnwHNDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Hsboaa1+E7DsNb6f6C0kJYwDg4acsKgLHlE3OyvJL6D+IkYbja7mezkZNRZ85YpOMSDkcqX8DqJEfo19GElkepNFv1PjabPbbvKfTS0TE28I/1Azb6LjPWY9vHtBzhzJmFkXS2eDJxXrKpUgpULP8u0zqQMWKEEeGVetB7H+LR+u6NAfXuX5kZcai2vUpTMJd2S8ADSpTdUATegYQFiTsTW+AKT3UBByetiTccNJ0OBiMaMyXtNqgmBa0JOOtfRdPvDXyvBmykf6p9Wm5g==,iv:5hlISdq3XBWvEheRl2BtOxSSKWAfKImyulwXb0DapNM=,tag:3wa/RSyWrfrOgvS3lbC3GA==,type:str]
    known_hosts: ENC[AES256_GCM,data:b9STAzLYTr3k0l3FlgyTQL+3KQeK15oC6uU8z8aiqfYxQ4M9/6XQPKm3ZMHWKjc187nuWLYLlXjSGh8yeeoNO6OCrtLwolBLukJfOc6MI6Ox/EUxIx2zEEoYob9nktfpjXAtX6fBopSQMonGTlElY/O+6HumdJj+HpUlooEkjeLT4BY1vLa8KE7XYrGrBCI6bNTAaBq2oVsnyFicFYPZd+MhnJK8kFOyXeyV,iv:GrRhlTo8Ji/RDwcLcZ/Aj+D/9raXZs7IOKn7dlej2ls=,tag:UMpL2iF6zmHYc56yv/MRxw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU2p3WGJBZUJHbmE1UUh6
            S2lUSGROZERESENBekx0d0krOGlKdk1EdFFRClU4aXpOYzk2MDF6di9jOG1FQWNk
            UUhkbXdGSWpJcXdmOWhFZ3V1bG4yVjQKLS0tIEtBRUdVTHpzQVF5VURVSDVHY1ZF
            THZFYjJNbU93eEpBS3hIUDVFTUhxbDgK+YVF7ePfCw1YOSi9Eau5nVAOAFBfVM7j
            3a/fcrHjowu1u8R3zj0Qu2igKdgR9tWajXbOYHpXTvapawnYc2TthQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:49:06Z"
    mac: ENC[AES256_GCM,data:nxtRrWU4jkjnMKbJSirj4bjtNEDR4H8C28zf0FLi4kB51qc3lNCTrIavXjB1UgGCPnOUI2FX3tn4CaF9cmvPXnM5QNGFRj/kXrDxj8bDI1s4YeMYz+BtYdxpxCyPtFAPx9tHuE6LfYBIwt8E6hCr8w+tUv1JXbPM7gpTHZwhUw4=,iv:BwQPKfR/hJqm99BtpHEtsZ7ndhriDXZ17+xND7CB+i0=,tag:I2Ww/ltiU/yHkfRcx5Jb/Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
