apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WcQH32PeUTt5B6+LvrwvlrI9EWB4uxQ/DvkLysEbBHUsCV62Dp5RmbiWxXwV/R/hrxim4pxVhBgIwVz5HsMeRQQxQfS9oiLmcnh3AJ9JDOcv3MQ7/WobeMFjQNVsn+kOoJOHbiDoWbW/i42N7v+qAIKXsrkCZcVlRzbtVlR/PeohMMORU1uBkQGmnaXm1O1IX1eoItQXc/tp24N0+yFw5RBWibWXnjr6FGDTVEMu6hUb05YWmzmg,iv:BsBBRkfV+v1Qf6TGbpluEfyMjoyrBjOxZaIWstvbPi0=,tag:eRz90uAmZLH2+gocOQ57jA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVk5qR0NkK1VtclhmbjBU
            cGlrVG4xS2JOb1dpb1l0NnFsajNUM1o4dWxvCjVabmpWWm1KbWk3cHgxUzNoNTBS
            SFNPK3ZOcW4za3VNRkxRVFBmV0c0QlEKLS0tIGw4ZmJwRlpmbGQ3azJOd0s4YmJY
            U1NaR1hJSmVTckxQclF5SGtjNGw1aWMKmAbNcaeGvss2RApphqk1ashuYi2mdMHM
            xfX+YKFs9TfaALN5pcY53wBTfO5u/Bb/nGbJKKWBKmj+0JxW3ZQtFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:42:02Z"
    mac: ENC[AES256_GCM,data:xYV2kTcPsrjkLe7NigNctemPwKOeMjGgcy47MOP9qXGAMRAgUYu64IGHHYXnC5AvehC5NHqPdTeF3xMqILJB6T5QmwCkvcmjh49I+GxPbGbZWxblGGpom0ZMEjQ8Dthy2gkXrveEdbGSK751dV9K/9MiAkXNXrzoaqFu1F3hl3A=,iv:ZyB0VPzrd+jWE6zAQu1TE0C7pQbfGYnutbD4/43+CRQ=,tag:en7bsn0iiLYDk7m+O5rtig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
