apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:jI/NHe11r4qji+f6U6+RmjppaZdax05taywnXfTiaO1+mYxuHsGZGd0WqwuFjoMxqEuaAZgmNGO/j2aMzTpre+mFBW+6g6B9M7bvFEv7GHtGIgPJTgUoNXEOqcSBPIfGjR1AddR33WHNZcPbjoQLL51487BUXBjkkHQh6ssvxR+mB2Pw3EpLMuyWq0LL15R+VmARG3zonFjDpTJjgQRDjHSLtJ83pqYvKSlsWBXt3ZvFvi8FVAyb,iv:8l8UiBHMdKAPESzuvNuqcRabNPYp3+BeCYh7AZj40XY=,tag:XL3S871DfVQEX7g7YWmf9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaEM0b3UxK28wcVJ0U1Ju
            UktleDJsa3QwSVNpRXJrWisrYXQ3d0MxalFzClNRUG1TNlN5bmw5cGZITzBaaDJU
            aUxvREZUUUFZbWhld1NkajRtd2I5RlUKLS0tIHM2VUYvZVc5YnNIMHFwZUJIekM5
            KzNaUW9RSzBKQThDK3ozQUl5ME9wYU0KHjWjY9X2b0zxAirdZscg2BdO4uQsSTvQ
            U040MCIFvNfBHVp3w5uAZdBo0uSwOPeI8vAV84j2AH8o2ICOxkY2NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T23:45:49Z"
    mac: ENC[AES256_GCM,data:eE0y+fGqONwT1owr6TNj1t9KSSFoqcomHJxUv6+7CF30NZyfQHYGEH0Bd3M2ilQ4pIe0svDA+Vx5LR0QAJRzaZ4Vv6LTYndis1epzdiWiQBuqctZT2o4ZdShZKoFGvTtSzYVty8j0JmXypxKrltXUAzUjTY4pEoArR33CeCH2Iw=,iv:X0qoH1WT+9iP983RGQrzFhn79WPjAzq5GumCOVfYXL8=,tag:kooBTd67dyHgYVc1hHDQDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
