apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:QZoq7BaKEzkzeiSAkHo0bVvRH330P4HYhsWs7gYcn2J5/dK/1PKoQLp6fBd58gkdj3apaDBYrimN1dRvkbub/6UR+dYIf1ZHJnxbYjFSqAkezdWW4Xk/G2FMd+YSSIeqOvM+Ab40njUrG1n0EVmbSX4bZlG7/WrpGMJTl92PKcbMLbRkYL5jByUBe0Bjm/18xpnK2EBo7Uw4am7WHDQbiWSUuGPBjVSjgLQwu/4O51sccTiMq2tR,iv:ghIkGx8AyYjdRyUZOFPEQR9WCcu0VehSwjGRGWkpzr0=,tag:uWjotE7RQihhZZruqbzdLA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRXNSTG1uckpsQVN5SjB5
            eFdCQTAyZFRWUnVlMzc2ZU9GZjd5aXduSm1BCllyQnFBSzdKdXpHNmJ5TnI4R3JT
            MTV0VkNhT3FrMGtNSHQyZGZmNWVaN00KLS0tIHhVTjQvV2lOMGdPZmIyZjhYY0dF
            UVVxMS80VlNZcStDRmRBYk84dnhDVjQKQyrPc3tsoWP0YICOHDDnMmwAprfgJp07
            qaepn5vA+HjQ6ZPPUI1xtHxeEmnZvXpYzvef0qiPiPuMBdVSq1c2SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T07:00:35Z"
    mac: ENC[AES256_GCM,data:u5HwIP0RCOM4+4Wx1avY2L9z8jITYh+WoEwg3capfmmvgaZhwM/hoSfQwk7hSwBtTtN85geAcrCDwZ74cHNRSsQSy+KcX/D+OYpbJpX+352ktic3+BIBtqXPbttrOxq/qWxh67b3GOISzO17lS3SppMrFJ2UxDiqZTiXFZ3OeSg=,iv:ptVxkcALDswvM0nf51E1i6GffICxBdWLt+sGBjlhhl4=,tag:MR+YDtZd/KTqjqA3Lqu78Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
