apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData:
    hmac_secret: ENC[AES256_GCM,data:SGBRfQ==,iv:b3DvolbJiDqdiAk8ziel+6Lbr2Gp06nIQmd/0d3yZhk=,tag:p80yN59pa+f9ek1q/3nwFg==,type:str]
    jwks_key.pem: ENC[AES256_GCM,data:fbKVMg==,iv:fh3JsjKwn3AZUGlcbxXtssl9zttnotw2vPtpEXIQsMQ=,tag:e8BSzteOnJVBXzVkWxKQIg==,type:str]
    immich: ENC[AES256_GCM,data:vcq8Yg==,iv:skU/ghEYEOiIeOyJ8urNHWFAml7RzvGgAzxns6P5vLI=,tag:fKH5GC7cV1v1bq0Ow18JUg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbUNSYUhVbWZrN25YMHB4
            NWRubCt0bVA3SWpZcnpFb1R3b01ZczBkNndrCjlGS0FMcm1qL0d2VS9uckZWMGNr
            dWRFODZJOEd0bzBiamNoSkJmMDZvUG8KLS0tICt2TjJvbnFSSW9MUS9xZmFIQjFM
            cFZYWE9vZlNoZEZsbkUxQmQ4QlVSQk0KRF31OG77giCUjBm2uhch4dwUXOWLJ9Kc
            UdVcPtSIjO6dvEpJ4b7OKYMzUYmy1isJf/CJ08qjl2GC1Hq+65pWFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:49:06Z"
    mac: ENC[AES256_GCM,data:tv2yKJXiNnS8wAlVhEIaUN7WB6ChPT5ea5UYCW8qVZ4si/vR2CwqJIYM8mcXo7ePIwx0Mbk4Ii6BeR2hGlsXaZJi7s3foDvSgluAQS2rWXlkxZ7Z421TEOryDpu+HoBDJst9xU2NfuKfIai5zXWKa9oAL+GYyYTT8U7NTvdmC6Q=,iv:t+rQmtTt3wjU4GbuS7uzZDcYv30cIGwf86ZFF5g3+x8=,tag:StDB/n4RY2RI8TGH4/oegQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
