apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData:
    hmac_secret: ENC[AES256_GCM,data:QXpiSg==,iv:KM+zwum7xKjNMq/dgUfyJ8t0a9RvWkKYMBZ2//Fy7/Y=,tag:BS+XELsNDWxR0cMcVN+FIQ==,type:str]
    jwks_key.pem: ENC[AES256_GCM,data:iQMBkg==,iv:EKDDQX4i9TFORDMhZkQrclwfHcjxAJpbKavNj+CRYPI=,tag:cUCgTTr3Ckbqn0ZrzyOa9g==,type:str]
    immich: ENC[AES256_GCM,data:tp50jA==,iv:Oi10TjgExx2vOTMwb5u3s4Zbjw6KQsLDlYBgw/Lohs8=,tag:1VnpvmCoHKHkEoV2c4CdvQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMTVQaENnRUJ6USsrbHNN
            bTgwVWhzMEJpRmZPVmZkNlJFQ28xRC8zaDA0CmNpTjAzR1dUQXpyUTJTVXRobUYv
            MXRvVzI3cFpLOWZhakEraTBtVWx3UFUKLS0tIGR6SFNwTXhJVm5WaHB0R2Vtdlhq
            YXlIamwxVk1wQzJRcWk1dE1ZNURhZDAKZL+NhiwKr0IDFrcIjB8id5PFMd4e4fPz
            0VrClmIHTJM7HHvniToXnu5InuZSqItQQoDBXCl0q86emWaZTzOJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T23:39:04Z"
    mac: ENC[AES256_GCM,data:J8ltnYgyqRskVu71/CO1MnLEd0LdzLE0CgPvzEDiJcYm4lJIYvQbEg//OfF83TKJ2qbSgDnpON65ATq3awv3Zs/g2SMVNLww2swdEPMoMvD1x6Dmgnvc+r3AqY8rwbRbjgqfhRX90uRFOHNYcGOjUwMK+smh1QMlpizHpHIzeC4=,iv:lpoenFy1NI4Vxatzln84sRPm5lC/2CAgiTk2rJ9uKUI=,tag:d2cFEG/fXv1MY6GTg/ik0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
