apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbGx2ZE1zclppMVNUdGhK
            NTNJZFozQjIxdm1tVUVGcmxwRTlRYXA2RjFRCjZadWhXcmFyZmY3bmZ0NXkwd2xE
            WnNlMHJ6S0YwaWpHL2VwQjc4ajNELzAKLS0tIFQrNm1udGQ2QjkzcTFud3duN2RN
            c1pnWjYySHBKazZ3b3JPaHdvVURHbFUKSqQPmau7QNlofWKX9aMfK8O7f7pvBLBm
            j67VqeKY6eoh4GYLOhapdg72teymFTf9xqqd/yILpBV27G8vQvHX9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:56:36Z"
    mac: ENC[AES256_GCM,data:KvdvOoYuOWysvLl/iAdcZYqpXH2mM3/4G0Ia9pZvJOBQuxOa3VBeEV0sBvB45dL28YaBfrZETMV+2s11iGokO0VKAHEDOv/MRARWqU1IVW6z5aRunSCHESc25QSxjlYD6L7gH0aQntRfGakRBaqcC0IZbVu7j+kfeJJ3xPhlJAA=,iv:TQdlvqNY4KAY+cClYiKMx3SNENqrQpgmVJkWLlSwTnE=,tag:/ZJaONBnVqxwaaVs/gw1Pg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
