---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: haos.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
    
    service:
      main:
        type: ExternalIP
        enabled: true
        externalIP: ${HAOS_IP}
        ports:
          main:
            enabled: true
            port: 8123
            protocol: http